### ISSUE TITLE
How to use sticker?

### ISSUE THREAD

**Issue by jersonjunior** [gfaraj/super-bot-whatsapp#5]
I would like to know how to send sticker

**Comment by jersonjunior** [comment]
I managed, after raising the super-bot, I would like to implement SendSticker using the WebWhatsapp-Wrapper project in python, could you give any tips?

**Comment by gfaraj** [comment]
You can copy the appropriate functions I added to wapi.js and try to call them from there. I'm not very familiar with that project to give you much tips, sorry. If you have a specific question about that, please let me know.
