### ISSUE TITLE
isReady Function

### ISSUE THREAD

**Issue by rodrigolmacedo** [gfaraj/super-bot-whatsapp#6]
Hi, nice work!!

when i start the project, all works fine, but never pass the verification isReady( if i read the qrcode manually that works).

![image](https://user-images.githubusercontent.com/7695045/81209158-865ff480-8fa6-11ea-91dd-74296445bc75.png)

` return !!window.Store && !!window.Store.Msg;
}`

never return true...

**Comment by gfaraj** [comment]
Hi there, unfortunately this requires that you capture the QR code with your phone the first time you start the app. The next time it should start up logged in. Is that not happening for you?

**Comment by rodrigolmacedo** [comment]
> 
> 
> Hi there, unfortunately this requires that you capture the QR code with your phone the first time you start the app. The next time it should start up logged in. Is that not happening for you?

no problem, thats works fine, thanks for the good job.
