### ISSUE TITLE
bot is not listening on 3000

### ISSUE THREAD

**Issue by nicoirm** [gfaraj/super-bot-whatsapp#9]
hi, 
i am trying to use the whatsapp bot from source, start ok, but when i send message to the bot i get this error

Error when contacting bot: Error: connect ECONNREFUSED 127.0.0.1:3000 Error: connect ECONNREFUSED 127.0.0.1:3000

and when i curl localhost:port

curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused

Thanks

**Comment by gfaraj** [comment]
Hi @nicoirm, I just noticed you opened and closed this issue. I assume you figured it out?
